################################################################################
# DigitalFlashCimIncGen
#
# MLIR DigitalFlashCim dialect generated includes.
################################################################################

add_custom_target(DigitalFlashCimIncGen)

# Attributes, Dialect, Operations and Types.
add_subdirectory(IR)
