################################################################################
# DigitalCimIncGen
#
# MLIR DigitalCim dialect generated includes.
################################################################################

add_custom_target(DigitalCimIncGen)

# Attributes, Dialect, Operations and Types.
add_subdirectory(IR)
